/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: typeof import('components/ui')['Button']
  const Input: typeof import('components/ui')['Input']
  const Select: typeof import('components/ui')['Select']
}
